<a href="https://colab.research.google.com/github/Juan-Vega18/GESTION_DE_DATOS/blob/main/TAREA_1_BASE_DE_DATOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TAREA GESTION DE DATOS
CON MIS PROPIOS DATOS

In [ ]:
import duckdb
import pandas as pd

In [ ]:
con = duckdb.connect()
print("Conexion creada ✅")

Conexion creada ✅

In [ ]:
con.sql

In [ ]:
df = pd.read_csv('/content/39._Enfermedades_crónicas_en_el_municipio_de_Bucaramanga_20260819.csv')

In [ ]:
df.head()

,ORDEN,Sexo,Regimen,Artritis,Diabetes,Hipertensión,EPOC,Asma,Insuficiencia cardiaca,Cáncer,...,Insuficiencia renal cronica,ERC TRR,Huerfanas- Hemofilias y otras Coag,Cirugia Cardiaca,Trasplantados,EAPB,COMUNA,BARRIO_VER,GRUPO_ ETAREO,CICLO_DE_VIDA
0,1,MASCULINO,S,2,1,1,2,2,2,2,...,NO,NO,2,2,2,ASMETSALUD,05. GARCIA ROVIRA,CHORRERAS DE DON JUAN,60 Y MAS,PERSONA MAYOR
1,2,MASCULINO,C,2,2,1,2,2,2,2,...,NO,NO,2,2,2,COOMEVA,12. CABECERA DEL LLANO,CABECERA DEL LLANO,60 Y MAS,PERSONA MAYOR
2,3,FEMENINO,C,2,1,2,2,2,2,2,...,NO,NO,2,2,2,COOSALUD,12. CABECERA DEL LLANO,ANTIGUO CAMPESTRE,60 Y MAS,PERSONA MAYOR
3,4,MASCULINO,P,2,1,1,2,2,2,2,...,NO,NO,2,2,2,ECOPETROL,03. SAN FRANCISCO,SAN RAFAEL,60 Y MAS,PERSONA MAYOR
4,5,MASCULINO,C,2,2,1,2,2,2,2,...,NO,NO,2,2,2,FAMISANAR,12. CABECERA DEL LLANO,CABECERA DEL LLANO,60 Y MAS,PERSONA MAYOR

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110693 entries, 0 to 110692
Data columns (total 22 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   ORDEN                               110693 non-null  int64
 1   Sexo                                110693 non-null  object
 2   Regimen                             110693 non-null  object
 3   Artritis                            110693 non-null  int64
 4   Diabetes                            110693 non-null  int64
 5   Hipertensión                        110693 non-null  int64
 6   EPOC                                110693 non-null  int64
 7   Asma                                110693 non-null  int64
 8   Insuficiencia cardiaca              110693 non-null  int64
 9   Cáncer                              110693 non-null  int64
 10  ERC                                 110693 non-null  object
 11  TIPO ERC                            110693 non-null  object
 12  Insuficiencia renal cronica         110693 non-null  object
 13  ERC TRR                             110693 non-null  object
 14  Huerfanas- Hemofilias y otras Coag  110693 non-null  int64
 15  Cirugia Cardiaca                    110693 non-null  int64
 16  Trasplantados                       110693 non-null  int64
 17  EAPB                                110693 non-null  object
 18  COMUNA                              110693 non-null  object
 19  BARRIO_VER                          110693 non-null  object
 20  GRUPO_ ETAREO                       110693 non-null  object
 21  CICLO_DE_VIDA                       110693 non-null  object
dtypes: int64(11), object(11)
memory usage: 18.6+ MB

In [ ]:
df.dtypes

ORDEN                                  int64
Sexo                                  object
Regimen                               object
Artritis                               int64
Diabetes                               int64
Hipertensión                           int64
EPOC                                   int64
Asma                                   int64
Insuficiencia cardiaca                 int64
Cáncer                                 int64
ERC                                   object
TIPO ERC                              object
Insuficiencia renal cronica           object
ERC TRR                               object
Huerfanas- Hemofilias y otras Coag     int64
Cirugia Cardiaca                       int64
Trasplantados                          int64
EAPB                                  object
COMUNA                                object
BARRIO_VER                            object
GRUPO_ ETAREO                         object
CICLO_DE_VIDA                         object
dtype: object

In [ ]:
con.sql("CREATE OR REPLACE TABLE enfermedades AS SELECT * FROM df")
con.sql("SELECT COUNT(*) AS total_filas FROM enfermedades").show()    #Cuéntame cuántas filas hay y le pone nombre a esa columna

┌─────────────┐
│ total_filas │
│    int64    │
├─────────────┤
│      110693 │
└─────────────┘

In [ ]:
con.sql("SELECT * FROM enfermedades LIMIT 5").show()    #Muéstrame las primeras 5 filas de la tabla contratos, con todas sus columnas

┌───────┬───────────┬─────────┬──────────┬──────────┬──────────────┬───────┬───────┬────────────────────────┬────────┬─────────┬──────────────┬─────────────────────────────┬─────────┬────────────────────────────────────┬──────────────────┬───────────────┬────────────┬────────────────────────┬───────────────────────┬───────────────┬───────────────┐
│ ORDEN │   Sexo    │ Regimen │ Artritis │ Diabetes │ Hipertensión │ EPOC  │ Asma  │ Insuficiencia cardiaca │ Cáncer │   ERC   │   TIPO ERC   │ Insuficiencia renal cronica │ ERC TRR │ Huerfanas- Hemofilias y otras Coag │ Cirugia Cardiaca │ Trasplantados │    EAPB    │         COMUNA         │      BARRIO_VER       │ GRUPO_ ETAREO │ CICLO_DE_VIDA │
│ int64 │  varchar  │ varchar │  int64   │  int64   │    int64     │ int64 │ int64 │         int64          │ int64  │ varchar │   varchar    │           varchar           │ varchar │               int64                │      int64       │     int64     │  varchar   │        varchar         │        varchar        │    varchar    │    varchar    │
├───────┼───────────┼─────────┼──────────┼──────────┼──────────────┼───────┼───────┼────────────────────────┼────────┼─────────┼──────────────┼─────────────────────────────┼─────────┼────────────────────────────────────┼──────────────────┼───────────────┼────────────┼────────────────────────┼───────────────────────┼───────────────┼───────────────┤
│     1 │ MASCULINO │ S       │        2 │        1 │            1 │     2 │     2 │                      2 │      2 │ SI      │ ERC SIN CLAS │ NO                          │ NO      │                                  2 │                2 │             2 │ ASMETSALUD │ 05. GARCIA ROVIRA      │ CHORRERAS DE DON JUAN │ 60 Y MAS      │ PERSONA MAYOR │
│     2 │ MASCULINO │ C       │        2 │        2 │            1 │     2 │     2 │                      2 │      2 │ SI      │ 2            │ NO                          │ NO      │                                  2 │                2 │             2 │ COOMEVA    │ 12. CABECERA DEL LLANO │ CABECERA DEL LLANO    │ 60 Y MAS      │ PERSONA MAYOR │
│     3 │ FEMENINO  │ C       │        2 │        1 │            2 │     2 │     2 │                      2 │      2 │ NO      │ NO           │ NO                          │ NO      │                                  2 │                2 │             2 │ COOSALUD   │ 12. CABECERA DEL LLANO │ ANTIGUO CAMPESTRE     │ 60 Y MAS      │ PERSONA MAYOR │
│     4 │ MASCULINO │ P       │        2 │        1 │            1 │     2 │     2 │                      2 │      2 │ NO      │ NO           │ NO                          │ NO      │                                  2 │                2 │             2 │ ECOPETROL  │ 03. SAN FRANCISCO      │ SAN RAFAEL            │ 60 Y MAS      │ PERSONA MAYOR │
│     5 │ MASCULINO │ C       │        2 │        2 │            1 │     2 │     2 │                      2 │      2 │ NO      │ NO           │ NO                          │ NO      │                                  2 │                2 │             2 │ FAMISANAR  │ 12. CABECERA DEL LLANO │ CABECERA DEL LLANO    │ 60 Y MAS      │ PERSONA MAYOR │
└───────┴───────────┴─────────┴──────────┴──────────┴──────────────┴───────┴───────┴────────────────────────┴────────┴─────────┴──────────────┴─────────────────────────────┴─────────┴────────────────────────────────────┴──────────────────┴───────────────┴────────────┴────────────────────────┴───────────────────────┴───────────────┴───────────────┘

In [ ]:
con.sql("SUMMARIZE enfermedades").show()  #max_rows=100

┌────────────────────────────────────┬─────────────┬──────────────────────────┬─────────────────────┬───────────────┬────────────────────┬─────────────────────┬─────────┬─────────┬─────────┬────────┬─────────────────┐
│            column_name             │ column_type │           min            │         max         │ approx_unique │        avg         │         std         │   q25   │   q50   │   q75   │ count  │ null_percentage │
│              varchar               │   varchar   │         varchar          │       varchar       │     int64     │      varchar       │       varchar       │ varchar │ varchar │ varchar │ int64  │  decimal(9,2)   │
├────────────────────────────────────┼─────────────┼──────────────────────────┼─────────────────────┼───────────────┼────────────────────┼─────────────────────┼─────────┼─────────┼─────────┼────────┼─────────────────┤
│ ORDEN                              │ BIGINT      │ 1                        │ 110493              │        100407 │ 55346.68198531072  │ 31953.912192370004  │ 27688   │ 55392   │ 83063   │ 110693 │            0.00 │
│ Sexo                               │ VARCHAR     │ FEMENINO                 │ NO DISPONIBLE       │             2 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ Regimen                            │ VARCHAR     │ C                        │ S                   │             5 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ Artritis                           │ BIGINT      │ 1                        │ 2                   │             2 │ 1.987370475097793  │ 0.11166974817768001 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ Diabetes                           │ BIGINT      │ 1                        │ 2                   │             2 │ 1.6458764330174447 │ 0.47824902777182016 │ 1       │ 2       │ 2       │ 110693 │            0.00 │
│ Hipertensión                       │ BIGINT      │ 1                        │ 2                   │             2 │ 1.2314690179144119 │ 0.42177330254778833 │ 1       │ 1       │ 1       │ 110693 │            0.00 │
│ EPOC                               │ BIGINT      │ 1                        │ 2                   │             2 │ 1.9471872656807567 │ 0.2236604599153419  │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ Asma                               │ BIGINT      │ 1                        │ 2                   │             2 │ 1.9835400612504857 │ 0.12723661194257224 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ Insuficiencia cardiaca             │ BIGINT      │ 1                        │ 2                   │             2 │ 1.9917880986150887 │ 0.09024710321271083 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ Cáncer                             │ BIGINT      │ 1                        │ 2                   │             2 │ 1.9544415636038412 │ 0.20852639664279768 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ ERC                                │ VARCHAR     │ NO                       │ SI                  │             2 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ TIPO ERC                           │ VARCHAR     │ 1                        │ SI                  │            36 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ Insuficiencia renal cronica        │ VARCHAR     │ NO                       │ SI                  │             2 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ ERC TRR                            │ VARCHAR     │ 2                        │ TMND                │            18 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ Huerfanas- Hemofilias y otras Coag │ BIGINT      │ 1                        │ 2                   │             2 │ 1.9913454328638667 │ 0.09262690275063254 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ Cirugia Cardiaca                   │ BIGINT      │ 1                        │ 2                   │             2 │ 1.9990152945534045 │ 0.03136470450878658 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ Trasplantados                      │ BIGINT      │ 1                        │ 2                   │             2 │ 1.998527458827568  │ 0.03834561354819761 │ 2       │ 2       │ 2       │ 110693 │            0.00 │
│ EAPB                               │ VARCHAR     │ ASMETSALUD               │ SURA                │            11 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ COMUNA                             │ VARCHAR     │ 01. NORTE                │ NO DISPONIBLE       │            24 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ BARRIO_VER                         │ VARCHAR     │ 10 DE MAYO SANTA BARBARA │ VIVEROS DE PROVENZA │           217 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ GRUPO_ ETAREO                      │ VARCHAR     │ 0 A 6                    │ 7  A 11             │             6 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
│ CICLO_DE_VIDA                      │ VARCHAR     │ ADOLESCENCIA             │ PRIMERA INFANCIA    │             6 │ NULL               │ NULL                │ NULL    │ NULL    │ NULL    │ 110693 │            0.00 │
├────────────────────────────────────┴─────────────┴──────────────────────────┴─────────────────────┴───────────────┴────────────────────┴─────────────────────┴─────────┴─────────┴─────────┴────────┴─────────────────┤
│ 22 rows                                                                                                                                                                                                    12 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
resumen = con.sql("SUMMARIZE enfermedades").df()
resumen[["column_name", "min", "max", "null_percentage"]]

,column_name,min,max,null_percentage
0,ORDEN,1,110493,0.0
1,Sexo,FEMENINO,NO DISPONIBLE,0.0
2,Regimen,C,S,0.0
3,Artritis,1,2,0.0
4,Diabetes,1,2,0.0
5,Hipertensión,1,2,0.0
6,EPOC,1,2,0.0
7,Asma,1,2,0.0
8,Insuficiencia cardiaca,1,2,0.0
9,Cáncer,1,2,0.0
10,ERC,NO,SI,0.0
11,TIPO ERC,1,SI,0.0
12,Insuficiencia renal cronica,NO,SI,0.0
13,ERC TRR,2,TMND,0.0
14,Huerfanas- Hemofilias y otras Coag,1,2,0.0
15,Cirugia Cardiaca,1,2,0.0
16,Trasplantados,1,2,0.0
17,EAPB,ASMETSALUD,SURA,0.0
18,COMUNA,01. NORTE,NO DISPONIBLE,0.0
19,BARRIO_VER,10 DE MAYO SANTA BARBARA,VIVEROS DE PROVENZA,0.0
20,GRUPO_ ETAREO,0 A 6,7 A 11,0.0
21,CICLO_DE_VIDA,ADOLESCENCIA,PRIMERA INFANCIA,0.0

In [ ]:
# Nombres reales de las columnas
con.sql("DESCRIBE enfermedades").show()

┌────────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│            column_name             │ column_type │  null   │   key   │ default │  extra  │
│              varchar               │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ ORDEN                              │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Sexo                               │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ Regimen                            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ Artritis                           │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Diabetes                           │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Hipertensión                       │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ EPOC                               │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Asma                               │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Insuficiencia cardiaca             │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Cáncer                             │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ ERC                                │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ TIPO ERC                           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ Insuficiencia renal cronica        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ ERC TRR                            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ Huerfanas- Hemofilias y otras Coag │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Cirugia Cardiaca                   │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ Trasplantados                      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ EAPB                               │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ COMUNA                             │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ BARRIO_VER                         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ GRUPO_ ETAREO                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ CICLO_DE_VIDA                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
├────────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┤
│ 22 rows                                                                        6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Todas mis columnas estan convenientemente llenas, contento por eso.

In [ ]:
con.sql("SELECT COMUNA FROM contratos LIMIT 20").show()

┌────────────────────────┐
│         COMUNA         │
│        varchar         │
├────────────────────────┤
│ 05. GARCIA ROVIRA      │
│ 12. CABECERA DEL LLANO │
│ 12. CABECERA DEL LLANO │
│ 03. SAN FRANCISCO      │
│ 12. CABECERA DEL LLANO │
│ 12. CABECERA DEL LLANO │
│ 12. CABECERA DEL LLANO │
│ 12. CABECERA DEL LLANO │
│ NO DISPONIBLE          │
│ 12. CABECERA DEL LLANO │
│ 01. NORTE              │
│ 13. ORIENTAL           │
│ 12. CABECERA DEL LLANO │
│ 13. ORIENTAL           │
│ 15. CENTRO             │
│ 03. SAN FRANCISCO      │
│ 12. CABECERA DEL LLANO │
│ 16. LAGOS DEL CACIQUE  │
│ 15. CENTRO             │
│ 13. ORIENTAL           │
├────────────────────────┤
│        20 rows         │
└────────────────────────┘

In [ ]:
con.sql("SELECT SUM(Trasplantados) FROM contratos").show()

┌────────────────────┐
│ sum(Trasplantados) │
│       int128       │
├────────────────────┤
│             221223 │
└────────────────────┘

In [ ]:
# Porcentaje de nulos por columna, ordenado de mayor a menor
resumen = con.sql("SUMMARIZE enfermedades").df()
resumen[["column_name", "null_percentage"]].sort_values("null_percentage", ascending=False).head(10)
#Todo llenisimo

              column_name  null_percentage
0                   ORDEN              0.0
1                    Sexo              0.0
2                 Regimen              0.0
3                Artritis              0.0
4                Diabetes              0.0
5            Hipertensión              0.0
6                    EPOC              0.0
7                    Asma              0.0
8  Insuficiencia cardiaca              0.0
9                  Cáncer              0.0

In [ ]:
# ¿El total de filas es igual al total de IDs unicos?
con.sql("""
    SELECT
        COUNT(*) AS total_filas,
        COUNT(DISTINCT COMUNA) AS comuna_unicos
    FROM enfermedades
""").show()

# Si total_filas > comuna_unicos, hay comunas repetidas
# en este caso, es logico, es una misma ciudad, mismo pais, etc. No lo tomaremos con error

┌─────────────┬───────────────┐
│ total_filas │ comuna_unicos │
│    int64    │     int64     │
├─────────────┼───────────────┤
│      110693 │            21 │
└─────────────┴───────────────┘

In [ ]:
# Buscamos todas las formas distintas en que aparece "ROVIRA"
con.sql("""
    SELECT DISTINCT COMUNA
    FROM enfermedades
    WHERE COMUNA ILIKE '%ROVIRA%'
""").show() #El dataset parece estar limpio

┌───────────────────┐
│      COMUNA       │
│      varchar      │
├───────────────────┤
│ 05. GARCIA ROVIRA │
└───────────────────┘

In [ ]:
con.sql("""
    SELECT COMUNA, COUNT(*) AS veces
    FROM enfermedades
    GROUP BY COMUNA
    HAVING COUNT(*) > 1
    ORDER BY veces DESC
    LIMIT 10
""").show()

#La comuna mas comun en el dataset es la COMUNA ORIENTAL.
# Pero predomina la gente que no pertenece a ninguna comuna/barrio.

┌────────────────────────┬───────┐
│         COMUNA         │ veces │
│        varchar         │ int64 │
├────────────────────────┼───────┤
│ NO DISPONIBLE          │ 23669 │
│ 13. ORIENTAL           │ 11457 │
│ 03. SAN FRANCISCO      │  9649 │
│ 15. CENTRO             │  9269 │
│ 12. CABECERA DEL LLANO │  8019 │
│ 07. LA CIUDADELA       │  5748 │
│ 06. LA CONCORDIA       │  4786 │
│ 04. OCCIDENTAL         │  4746 │
│ 10. PROVENZA           │  4713 │
│ 05. GARCIA ROVIRA      │  4601 │
├────────────────────────┴───────┤
│ 10 rows              2 columns │
└────────────────────────────────┘